### ISSUE TITLE
chore: update to Angular 13

### ISSUE THREAD

**Issue by NachoVazquez** [ngworker/lumberjack#130]
## The Problem

The lumberjack project is lagging behind in its Angular version. Currently, it is in version 11.

This will be necessary to start supporting partial Ivy compilation.

## The Goals

Convert the Lumberjack repository to the latest version of Angular.

## Tasks

- [ ] Migrate to the latest version of Angular, TypeScript, RxJS, and Zone.js
- [ ] Migrate to a compatible version of Jest
- [ ] Migrate Schematics to a compatible version
- [ ] Verify that sonar works by introducing a lint error

**Comment by LayZeeDK** [comment]
If I recall correctly, Angular 13 does not support building View Engine-compatible library bundles. This means that we cannot upgrade to an Angular 13 workspace without releasing a new major version of Lumberjack.

**Comment by NachoVazquez** [comment]
Good catch! We will do it like that.

**Comment by LayZeeDK** [comment]
Fixed by #136
