### ISSUE TITLE
docs: create Lumberjack documentation website

### ISSUE THREAD

**Issue by NachoVazquez** [ngworker/lumberjack#132]
## The Problem

Lumberjack doesn't have a proper documentation website.

## The Goal

Create a Lumberjack documentation website like the spectacular one.

## Tasks

- [x]  Create and configure Docusaurus documentation website
- [x] Deploy to Github Pages
- [x] Configure CI/CD
- [x] Write proper documentation using the tools format

**Comment by LayZeeDK** [comment]
See [spectacular-docs](https://github.com/ngworker/ngworker/tree/main/packages/spectacular-docs).
